### ISSUE TITLE
Enable PS5 compatibility

### ISSUE THREAD

**Issue by snipem** [hthiery/python-ps4#13]
With the upcoming release of the PS5, we should check the compatibility with the PS5. Since Remote Play is supported with the same app there is room for hope that the PS5 will respond the same way as the PS4 on local network broadcasts. I will have look at it.

**Comment by snipem** [comment]
Does not work with PS5:
I used the IP address of my PS5.

```python
>>> playstation = pyps4.Ps4("192.168.178.119", broadcast=False)
>>> playstation
<pyps4.ps4.Ps4 object at 0x7fea394ead50>
>>> playstation.get_running_app_name()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/matze/.local/lib/python2.7/site-packages/pyps4/ps4.py", line 192, in get_running_app_name
    return self.get_status()['running-app-name']
  File "/home/matze/.local/lib/python2.7/site-packages/pyps4/ps4.py", line 71, in get_status
    return get_status(self._host)
  File "/home/matze/.local/lib/python2.7/site-packages/pyps4/ddp.py", line 102, in get_status
    ps_list = search(host=host)
  File "/home/matze/.local/lib/python2.7/site-packages/pyps4/ddp.py", line 91, in search
    data, addr = _send_recv_msg(host, broadcast, msg)
  File "/home/matze/.local/lib/python2.7/site-packages/pyps4/ddp.py", line 80, in _send_recv_msg
    return sock.recvfrom(1024)
socket.timeout: timed out
```

**Comment by snipem** [comment]
Here is an example for ps5-wake but it is also lacking the running app name: https://github.com/iharosi/ps5-wake
